/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.Carreras;
import Logica.Usuario;
import Logica.equipos;
import Logica.operadores;
import Modelo.CarrerasDAO;
import Modelo.EquiposDAO;
import Modelo.OperadoresDAO;
import Modelo.UsuariosDAO;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp-laptop
 */
public class Dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard1() {
        initComponents();
        this.setLocationRelativeTo(null);
        manejarCambioDePestaña(MainPanel, Filtrar, Ordenar, EquiposPanel, CarrerasPanel);
        postInitComponents();
    }
    
    private void postInitComponents() {
        
        MainPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                cargarInformacion();
            }
        });
    }
    private void manejarCambioDePestaña(JTabbedPane tabbedPane, JComboBox<String> comboBoxFiltrar, JComboBox<String> comboBoxOrdenar, JPanel equiposPanel, JPanel carrerasPanel) {
    tabbedPane.addChangeListener(e -> {
        int indiceSeleccionado = tabbedPane.getSelectedIndex();
        if (indiceSeleccionado == tabbedPane.indexOfComponent(EquiposPanel) ||
            indiceSeleccionado == tabbedPane.indexOfComponent(CarrerasPanel)) {
            comboBoxFiltrar.setVisible(false);
            comboBoxOrdenar.setVisible(false);
        } else {
            comboBoxFiltrar.setVisible(true);
            comboBoxOrdenar.setVisible(true);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CPANEL = new javax.swing.JLabel();
        ImportarButton = new javax.swing.JButton();
        ExportarButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        InsertarButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();
        Filtrar = new javax.swing.JComboBox<>();
        Ordenar = new javax.swing.JComboBox<>();
        MainPanel = new javax.swing.JTabbedPane();
        OperadoresPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OperadoresT = new javax.swing.JTable();
        EquiposPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EquiposT = new javax.swing.JTable();
        UsuariosPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        UsuariosT = new javax.swing.JTable();
        CarrerasPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CarrerasT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 640));

        jPanel1.setBackground(new java.awt.Color(39, 39, 39));

        CPANEL.setBackground(new java.awt.Color(245, 247, 248));
        CPANEL.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        CPANEL.setForeground(new java.awt.Color(245, 247, 248));
        CPANEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CPANEL.setText("CPANEL");

        ImportarButton.setText("Importar");
        ImportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarButtonActionPerformed(evt);
            }
        });

        ExportarButton.setText("Exportar");
        ExportarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarButtonActionPerformed(evt);
            }
        });

        SalirButton.setBackground(new java.awt.Color(51, 51, 51));
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CPANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImportarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExportarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(CPANEL)
                .addGap(140, 140, 140)
                .addComponent(ImportarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExportarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 247, 248));

        InsertarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InsertarButton.setText("Insertar");
        InsertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarButtonActionPerformed(evt);
            }
        });

        ActualizarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ActualizarButton.setText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        EliminarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EliminarButton.setText("Eliminar");

        Filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por", "Nombre", "Apellido", "Cédula" }));
        Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarActionPerformed(evt);
            }
        });

        Ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar", "ASC", "DESC", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ordenar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InsertarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ActualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MainPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        MainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainPanelMouseClicked(evt);
            }
        });

        OperadoresT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(OperadoresT);

        javax.swing.GroupLayout OperadoresPanelLayout = new javax.swing.GroupLayout(OperadoresPanel);
        OperadoresPanel.setLayout(OperadoresPanelLayout);
        OperadoresPanelLayout.setHorizontalGroup(
            OperadoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        OperadoresPanelLayout.setVerticalGroup(
            OperadoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        MainPanel.addTab("Operadores", OperadoresPanel);

        EquiposT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoría", "Descripción", "Estado", "Modelo", "Placa Inventario", "Fecha compra"
            }
        ));
        jScrollPane2.setViewportView(EquiposT);

        javax.swing.GroupLayout EquiposPanelLayout = new javax.swing.GroupLayout(EquiposPanel);
        EquiposPanel.setLayout(EquiposPanelLayout);
        EquiposPanelLayout.setHorizontalGroup(
            EquiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        EquiposPanelLayout.setVerticalGroup(
            EquiposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        MainPanel.addTab("Equipos", EquiposPanel);

        UsuariosT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Correo", "Tipo de usuario", "Carrera"
            }
        ));
        jScrollPane3.setViewportView(UsuariosT);

        javax.swing.GroupLayout UsuariosPanelLayout = new javax.swing.GroupLayout(UsuariosPanel);
        UsuariosPanel.setLayout(UsuariosPanelLayout);
        UsuariosPanelLayout.setHorizontalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        UsuariosPanelLayout.setVerticalGroup(
            UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        MainPanel.addTab("Usuarios", UsuariosPanel);

        CarrerasT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        jScrollPane4.setViewportView(CarrerasT);

        javax.swing.GroupLayout CarrerasPanelLayout = new javax.swing.GroupLayout(CarrerasPanel);
        CarrerasPanel.setLayout(CarrerasPanelLayout);
        CarrerasPanelLayout.setHorizontalGroup(
            CarrerasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        CarrerasPanelLayout.setVerticalGroup(
            CarrerasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        MainPanel.addTab("Carreras", CarrerasPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void ExportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarButtonActionPerformed
        Exportar1 exportar = new Exportar1();
        exportar.setVisible(true);
    }//GEN-LAST:event_ExportarButtonActionPerformed

    private void ImportarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarButtonActionPerformed
        Importar1 importar = new Importar1();
        importar.setVisible(true);
    }//GEN-LAST:event_ImportarButtonActionPerformed

    private void FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltrarActionPerformed

    private void MainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainPanelMouseClicked
        
    }//GEN-LAST:event_MainPanelMouseClicked

    private void InsertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarButtonActionPerformed
        switch (obtenerPanelActual()) {
            case "Operadores":
                InsertarOperador1 window = new InsertarOperador1();
                window.setVisible(true);
                break;
            case "Equipos":
                InsertarEquipo1 window1 = new InsertarEquipo1();
                window1.setVisible(true);
                break;
            case "Usuarios":
                 InsertarUsuario1 window2 = new InsertarUsuario1();
                window2.setVisible(true);
                break;
            case "Carreras":
                InsertarCarrera1 window3 = new InsertarCarrera1();
                window3.setVisible(true);
                break;
            default:
                
                break;
        }
    }//GEN-LAST:event_InsertarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
      switch (obtenerPanelActual()) {
            case "Operadores":
                ActualizarOperadores1 window = new ActualizarOperadores1();
                window.setVisible(true);
                break;
            case "Equipos":
                ActualizarEquipo1 window1 = new ActualizarEquipo1();
                window1.setVisible(true);
                break;
            case "Usuarios":
                 ActualizarUsuario1 window2 = new ActualizarUsuario1();
                window2.setVisible(true);
                break;
            case "Carreras":
                ActualizarCarrera1 window3 = new ActualizarCarrera1();
                window3.setVisible(true);
                break;
            default:
                
                break;
        }
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    public String obtenerPanelActual() {
    int selectedIndex = MainPanel.getSelectedIndex();
    String selectedPanel = MainPanel.getTitleAt(selectedIndex);
    return selectedPanel;
}

    private void cargarInformacion() {
    try {
        int indiceSeleccionado = MainPanel.getSelectedIndex();
        switch (indiceSeleccionado) {
            case 0: // OperadoresPanel
                cargarInformacionOperadores();
                break;
            case 1: // EquiposPanel
                cargarInformacionEquipos();
                break;
            case 2: // UsuariosPanel
                cargarInformacionUsuarios();
                break;
            case 3: // CarrerasPanel
                cargarInformacionCarreras();
                break;
            default:
                // Maneja el caso por defecto si es necesario
                break;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void cargarInformacionCarreras() throws Exception {
    DefaultTableModel model = (DefaultTableModel) CarrerasT.getModel();
    model.setRowCount(0); // Limpia las filas existentes
    CarrerasDAO DAO = new Carreras();
    List<Carreras> listaCarreras = DAO.mostrar(); 
    listaCarreras.forEach(c -> model.addRow(new Object[]{c.getIdcarrera(), c.getNombre_carrera()}));
}

private void cargarInformacionUsuarios() throws Exception {
    DefaultTableModel model = (DefaultTableModel) UsuariosT.getModel();
    model.setRowCount(0); // Limpia las filas existentes
    UsuariosDAO DAO = new Usuario(); 
    List<Usuario> listaUsuarios = DAO.mostrar(); // Asume que obtienes la lista de usuarios
    listaUsuarios.forEach(u -> model.addRow(new Object[]{
        u.getCedula(),
        u.getPrimer_nombre(),
        u.getPrimer_apellido(),
        u.getTelefono(),
        u.getCorreo(),
        u.getTipousuario(),
        u.getIdcarrera()
    }));
}

private void cargarInformacionEquipos() throws Exception {
    DefaultTableModel model = (DefaultTableModel) EquiposT.getModel();
    model.setRowCount(0); // Limpia las filas existentes
    EquiposDAO DAO = new equipos();
    List<equipos> listaEquipos = DAO.mostrar(); // Asume que obtienes la lista de equipos
    listaEquipos.forEach(e -> model.addRow(new Object[]{
        e.getIdequipo(),
        e.getIdcategoria(),
        e.getDescripcion(),
        e.getIdestado_equipo(),
        e.getModelo(),
        e.getPlaca_inventario(),
        e.getFecha_compra()
    }));
}

private void cargarInformacionOperadores() throws Exception {
    DefaultTableModel model = (DefaultTableModel) OperadoresT.getModel();
    model.setRowCount(0); // Limpia las filas existentes
    OperadoresDAO DAO = new operadores();
    List<operadores> listaOperadores = DAO.mostrar(); // Asume que obtienes la lista de operadores
    listaOperadores.forEach(o -> model.addRow(new Object[]{
        o.getCedula(),
        o.getPrimer_nombre(),
        o.getPrimer_apellido()
    }));
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JLabel CPANEL;
    private javax.swing.JPanel CarrerasPanel;
    private javax.swing.JTable CarrerasT;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JPanel EquiposPanel;
    private javax.swing.JTable EquiposT;
    private javax.swing.JButton ExportarButton;
    private javax.swing.JComboBox<String> Filtrar;
    private javax.swing.JButton ImportarButton;
    private javax.swing.JButton InsertarButton;
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JPanel OperadoresPanel;
    private javax.swing.JTable OperadoresT;
    private javax.swing.JComboBox<String> Ordenar;
    private javax.swing.JButton SalirButton;
    private javax.swing.JPanel UsuariosPanel;
    private javax.swing.JTable UsuariosT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
